apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: bot-observer-apirule
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    path: /.*
  service:
    host: bot-observer
    name: bot-observer-service
    port: 3000